spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://pgsql01:5432/xchange?currentSchema=calisma
    username: admin
    password: simon
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      poolName: SpringBootJPAHikariCP
      maxLifetime: 2000000
      connectionTimeout: 30000
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
    open-in-view: false
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level ${HOSTNAME} [%t] %C - %msg%n'
  level:
    root: INFO